<?php
/**
 * Maverick Logs Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to m.nahhas@live.fr so we can send you a copy immediately.
 *
 * You free to edit or add to this file your own code
 * github : https://github.com/maverick193/Maverick-Logs-Manager.git
 *
 * @version     0.1.0
 * @category    Maverick
 * @package     Maverick_Logs
 * @copyright   Copyright (c) 2012 Maverick-dev Inc. (http://maverick-dev.fr)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Maverick_Logs_Block_Adminhtml_Notification
 */
?>
<?php if ($this->canBeShown()): ?>
    <script type="text/javascript">
    //<![CDATA[
        var messagePopupClosed = false;
        function openMessagePopup() {
            var height = $('html-body').getHeight();
            $('message-popup-window-mask').setStyle({'height':height+'px'});
            toggleSelectsUnderBlock($('message-popup-window-mask'), false);
            Element.show('message-popup-window-mask');
            $('message-popup-window').addClassName('show');
        }
    
        function closeMessagePopup() {
            toggleSelectsUnderBlock($('message-popup-window-mask'), true);
            Element.hide('message-popup-window-mask');
            $('message-popup-window').removeClassName('show');
            messagePopupClosed = true;
        }
    
        Event.observe(window, 'load', openMessagePopup);
        Event.observe(window, 'keyup', function(evt) {
            if(messagePopupClosed) return;
            var code;
            if (evt.keyCode) code = evt.keyCode;
            else if (evt.which) code = evt.which;
            if (code == Event.KEY_ESC) {
                closeMessagePopup();
            }
        });
    //]]>
    </script>
    <div id="message-popup-window-mask" style="display:none;"></div>
    <div id="message-popup-window" class="message-popup">
        <div class="message-popup-head">
            <a href="#" onclick="closeMessagePopup(); return false;" title="<?php echo $this->getCloseText(); ?>"><span><?php echo $this->getCloseText(); ?></span></a>
            <h2><?php echo $this->getHeaderText(); ?></h2>
        </div>
        <div class="message-popup-content">
            <div class="message">
                <span class="message-icon message-<?php echo $this->getSeverityText();?>" style="background-image:url(<?php echo $this->getSeverityIconsUrl() ?>);"><?php echo $this->getSeverityText();?></span>
                <p class="logs-message-text"><?php echo $this->getNoticeMessageText(); ?></p>
                <?php $logList = $this->getLogList(); ?>
                <ul style="margin-left:90px;">
                    <?php foreach ($logList as $log): ?>
                        <li style="list-style-type: disc;"><?php echo $log; ?></li>
                    <?php endforeach;?>
                </ul>
            </div>
            <p class="read-more"><a href="<?php echo $this->getNoticeMessageUrl(); ?>" onclick="this.target='_blank';"><?php echo $this->getReadDetailsText(); ?></a></p>
        </div>
    </div>
<?php endif; ?>
